Repository googleapis/nodejs-monitoring, pull requests merged in 2020-07, with the labels that each got.

#450 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#451 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#453 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#455 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#459 build: missing closing paren in publish script and delete node 8 tests
  .kokoro/publish.sh
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial

#458 chore: delete node 8 test templates
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#460 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#462 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#463 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#464 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#466 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#467 build: update protos
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#468 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
