Repository googleapis/nodejs-monitoring, pull requests merged in 2020-05, with the labels that each got.

#427 feat: add Blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#429 fix: regen protos and tests, formatting
  protos/protos.js
  synth.metadata
  test/gapic_alert_policy_service_v3.ts
  test/gapic_group_service_v3.ts
  test/gapic_metric_service_v3.ts
  test/gapic_notification_channel_service_v3.ts
  test/gapic_service_monitoring_service_v3.ts
  test/gapic_uptime_check_service_v3.ts
Labels: automerge, cla: yes

#430 refactor!: Drop support for TimeSeriesQueryLanguageCondition as an alert condition type
  protos/google/monitoring/v3/alert.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#431 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#433 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#434 build: changed imports in protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none
