Repository googleapis/nodejs-monitoring, pull requests merged in 2020-12, with the labels that each got.

#508 chore: generate GAPIC metadata JSON file
  src/v3/gapic_metadata.json
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#507 fix: update alert policies one at a time because (concurrent updates are not supported)
  samples/alerts.js
  samples/metrics.js
  samples/quickstart.js
  samples/test/alerts.test.js
  samples/test/metrics.test.js
  samples/test/uptime.test.js
  samples/uptime.js
Labels: api: monitoring, cla: yes

#511 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: monitoring, cla: yes, context: partial
