Repository googleapis/nodejs-monitoring, pull requests merged in 2020-11, with the labels that each got.

#495 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#497 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v3/alert_policy_service_client.ts
  src/v3/group_service_client.ts
  src/v3/metric_service_client.ts
  src/v3/notification_channel_service_client.ts
  src/v3/service_monitoring_service_client.ts
  src/v3/uptime_check_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: monitoring, automerge, cla: yes

#496 build: add version clients
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: none

#501 fix(browser): check for fetch on window
  protos/protos.json
  src/v3/alert_policy_service_client.ts
  src/v3/group_service_client.ts
  src/v3/metric_service_client.ts
  src/v3/notification_channel_service_client.ts
  src/v3/service_monitoring_service_client.ts
  src/v3/uptime_check_service_client.ts
  synth.metadata
Labels: api: monitoring, cla: yes, context: partial

#504 build: stop tracking generated files
  src/v3/notification_channel_service_client.ts
  synth.metadata
Labels: api: monitoring, cla: yes, context: none

#505 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full
